// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import {defineConfig} from "prisma/config";

let DATABASE_URL;

if (process.env.NODE_ENV === "development") {
  DATABASE_URL = process.env.DATABASE_URL_DEV;
} else {
  DATABASE_URL = process.env.DATABASE_URL_PROD;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "node prisma/seed.js",
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
